### ISSUE TITLE
Strange Incompatibility With Incendium.

### ISSUE THREAD

**Issue by SnazzyJovialWyrm** [Steveplays28/realisticsleep#41] opened 2023-07-31 04:49 UTC
For some reason, version 1.7.1 of Realistic Sleep seems to be incompatible with any version of Incendium on 1.19.2, using Fabric. When both mods are installed, world generation/loading gets stuck at 100% and hangs there, but the game does not stop responding or freeze up. Instead, it simply just sits at 100%. I have to force close the game because of it. No crash log to boot with this problem since the game isn't crashing at all, so all I have to show is the latest.log file I sent to the Incendium devs.
[latest (1).log](https://github.com/Steveplays28/realisticsleep/files/12211545/latest.1.log)

**Comment by Steveplays28** [comment] 2023-07-31 05:11
Duplicate of #37. Not sure what causes this, I'll do some investigating in ~2 weeks.
Thanks for the report though.

**Closed** 2023-07-31 05:11 UTC
Labels: bug, compat
