### ISSUE TITLE
Not speeding up time.

### ISSUE THREAD

**Issue by BruhKidBruh** [Steveplays28/realisticsleep#60] opened 2024-02-13 06:50 UTC
[Uploading latest.log…]()

**Comment by Steveplays28** [comment] 2024-02-13 07:44
Your `latest.log` didn't get uploaded properly. Could you re-upload it?
Also, is this still the issue of your main world not working, or a different issue?

**Comment by BruhKidBruh** [comment] 2024-02-13 08:44
still only my main world

**Comment by BruhKidBruh** [comment] 2024-02-13 08:44
[latest.log](https://github.com/Steveplays28/realisticsleep/files/14258229/latest.log)

**Comment by Steveplays28** [comment] 2024-02-13 08:46
You have a bunch of errors in your log related to packet handlers.
Could you try doing a binary search to see if it's a mod incompatibility?

**Comment by BruhKidBruh** [comment] 2024-02-16 02:09
bro im like 11 get out of here with that binary search stuff😭

**Comment by Steveplays28** [comment] 2024-02-16 11:54
This is a binary search:
![Binary search GIF](https://media1.tenor.com/m/Jl0YrqxnHmAAAAAd/binary-search-sequence-search.gif)
It allows you to find mod incompatibilities more quickly by repeatedly toggling half of your mods, until you find the issue.

**Comment by BruhKidBruh** [comment] 2024-02-16 13:23
what file do i use a binary search on?

**Comment by Steveplays28** [comment] 2024-02-16 13:30
Your mods. Toggle them all off, then toggle on half. If the issue still occurs, toggle off half of that half, etc.

**Comment by Steveplays28** [comment] 2024-02-16 13:41
I should add that if what you said is true, you're not allowed to have a GitHub account.
Minimum age is 13 years old, see [GitHub's TOS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).

**Comment by BruhKidBruh** [comment] 2024-02-16 14:05
no im just stupid

**Comment by BruhKidBruh** [comment] 2024-02-16 14:07
So do i just move half of the mods out of my folder run the game then put them back in?

**Comment by Steveplays28** [comment] 2024-02-16 14:20
Yeah, then try half of that half, and repeat until you've found the problem.

**Comment by BruhKidBruh** [comment] 2024-02-16 14:48
okay ty ill try that

**Comment by MopsTMC** [comment] 2024-02-19 13:12
I'm having a similar issue after changing the config where the console gets spammed with the following errors when someone sleeps.

<details closed>

```
[14:46:01] [Netty Epoll Server IO #11/ERROR]: Error receiving packet 105
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.method_54160()" because "$$0" is null
	at net.minecraft.class_8824.method_54172(class_8824.java:174) ~[server-intermediary.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_8824$Anonymous$c72cfda5fa8844bc935100df29d592c9.encode(ComponentSerializationMixin.java:65) ~[?:?]
	at net.minecraft.class_8824$Anonymous$c72cfda5fa8844bc935100df29d592c9.encode(ComponentSerializationMixin.java:48) ~[?:?]
	at net.minecraft.class_5699$class_8741.encode(class_5699.java:517) ~[server-intermediary.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_2540.method_29172(class_2540.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_10805(class_2540.java:505) ~[server-intermediary.jar:?]
	at net.minecraft.class_7439.method_11052(class_7439.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:15) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:321) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:316) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:58:22] [Netty Epoll Server IO #8/ERROR]: Error receiving packet 105
java.lang.NullPointerException: null
[14:58:22] [Netty Epoll Server IO #11/ERROR]: Error receiving packet 105
java.lang.NullPointerException: null
[14:58:22] [Netty Epoll Server IO #8/WARN]: An exception was thrown by net.minecraft.class_2535$$Lambda$8219/0x00007f1614ff0480.operationComplete()
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.method_10858(int)" because "$$0" is null
	at net.minecraft.class_3222.method_43507(class_3222.java:1479) ~[server-intermediary.jar:?]
	at net.minecraft.class_7648$2.method_45086(class_7648.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_45082(class_2535.java:327) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:316) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:58:22] [Netty Epoll Server IO #11/WARN]: An exception was thrown by net.minecraft.class_2535$$Lambda$8219/0x00007f1614ff0480.operationComplete()
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.method_10858(int)" because "$$0" is null
	at net.minecraft.class_3222.method_43507(class_3222.java:1479) ~[server-intermediary.jar:?]
	at net.minecraft.class_7648$2.method_45086(class_7648.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_45082(class_2535.java:327) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:316) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

</details>

**Comment by Steveplays28** [comment] 2024-02-19 13:49
Hi @MopsTMC, could you try reproducing this issue with only Realistic Sleep and Fabric/Quilt API installed?

**Comment by MopsTMC** [comment] 2024-02-20 14:08
I tried reproducing it on a local server because I can't mess with the production one and I couldn't reproduce the issue even with the same mods and configuration. I will try adding the mod back at some point on the original server and see if I can figure out

**Comment by Steveplays28** [comment] 2024-04-20 11:14
Closing because the issues were not reproducible.

**Closed as not planned by Steveplays28** 2024-04-20 11:14 UTC
Labels: bug, question, unable to reproduce
