### ISSUE TITLE
Incompatibility: Realistic Sleep (v 1.7.1+mc1.20.x) and Incendium (v 5.3.0) on Minecraft Fabric 1.20.1

### ISSUE THREAD

**Issue by artem-mateush** [Steveplays28/realisticsleep#37] opened 2023-07-08 14:47 UTC
The game hangs on world generation.

**Comment by Steveplays28** [comment] 2023-07-08 14:48
Seems related to #32. I'll try to figure out what's causing this.

**Comment by deideloo** [comment] 2023-07-28 02:54
Same incompatibility on 1.19.2, worldgen goes through but the server hangs on stop command.

**Comment by Steveplays28** [comment] 2023-07-28 11:08
Could you guys try lowering the tick speed multipliers and seeing if the problem persists?
I still can't recreate this scenario.

**Comment by SnazzyJovialWyrm** [comment] 2023-07-31 13:52
> Could you guys try lowering the tick speed multipliers and seeing if the problem persists? I still can't recreate this scenario.

I hadn't messed with the tick speed multiplier or any other world generation settings for that matter while trying to create new worlds.

**Comment by Steveplays28** [comment] 2023-08-17 14:25
https://mclo.gs/mJWaoVQ I've done some testing, it appears like it gets stuck on starting the integrated server.
Not sure why this happens yet.

**Comment by Cinnius** [comment] 2023-08-17 14:47
The issue is present even with the new version (Realistic Sleep 1.8.1 and Incendium 5.3.1) on Quilt 0.19.4 for minecraft 1.20.1

**Comment by Steveplays28** [comment] 2023-08-17 14:48
Yeah, that release addresses a different issue (#40).

**Comment by Steveplays28** [comment] 2023-08-17 15:06
Could you guys try this [build](https://github.com/Steveplays28/realisticsleep/actions/runs/5892638979)?

**Comment by Cinnius** [comment] 2023-08-17 15:22
> Could you guys try this [build](https://github.com/Steveplays28/realisticsleep/actions/runs/5892638979), once it finishes?

Tried the build and the game work correctly, i tried:
- To load the game and start a world previously created.
- To sleep for testing if the game accelerated correctly (Tested on Furnace smelting and Wheat growing).

**Comment by Steveplays28** [comment] 2023-08-17 15:23
Awesome! Thanks for testing, I suppose the issue is resolved then.
I'm not sure if the fix will break something from vanilla, because I removed some vanilla event scheduling code, but we'll see!

I'll release this as a hotfix.

**Comment by Cinnius** [comment] 2023-08-17 15:26
For the test i tried there wasn't any problem, but when i have time i will play and if i find something strange i will tell you

Thanks for the work!

**Comment by Steveplays28** [comment] 2023-08-17 19:49
The fix has been released in [`v1.8.1`](https://github.com/Steveplays28/realisticsleep/releases/latest)!

**Closed by Steveplays28** 2023-08-17 19:49 UTC
Labels: bug, compat
